name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    uses: ./.github/workflows/ci-linux.yml

  windows:
    name: Windows
    uses: ./.github/workflows/ci-windows.yml

  macos:
    name: macOS
    uses: ./.github/workflows/ci-macos.yml
